export const TEXT_TO_SPEECH_REQUEST = 'TEXT_TO_SPEECH_REQUEST';
export const TEXT_TO_SPEECH_SUCCESS = 'TEXT_TO_SPEECH_SUCCESS';
export const TEXT_TO_SPEECH_ERROR = 'TEXT_TO_SPEECH_ERROR';

export const GET_RESULT_REQUEST = 'GET_RESULT_REQUEST';
export const GET_RESULT_SUCCESS = 'GET_RESULT_SUCCESS';
export const GET_RESULT_ERROR = 'GET_RESULT_ERROR';

export const GET_STATUS_REQUEST = 'GET_STATUS_REQUEST';
export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS';
export const GET_STATUS_ERROR = 'GET_STATUS_ERROR';

export const APP_WAITING = 'APP_WAITING';
export const APP_READY = 'APP_READY';

export const SELECT_VIDEO_ID = 'SELECT_VIDEO_ID';
export const SET_VIDEO_ID = 'SET_VIDEO_ID';
